name: flutter_application_1
description: "TPS 3R Brama Muda Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client untuk API
  http: ^1.2.0

  # Local Storage untuk Token
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Image Upload
  image_picker: ^1.1.2
  
  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700