<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Fungsi ini digunakan untuk mengisi database dengan banyak lowongan pekerjaan dummy yang bervariasi.
     */
    public function run(): void
    {
        // Bersihkan data lowongan sebelumnya untuk menghindari duplikasi
        Schema::disableForeignKeyConstraints();
        Job::truncate();
        Schema::enableForeignKeyConstraints();

        $jobs = [
            // === ADMINISTRASI ===
            [
                'title' => 'Staff Administrasi Gudang',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Bekasi',
                'qualification' => "1. Pria/Wanita, usia maks 28 tahun\n2. Pendidikan min. SMA/SMK sederajat\n3. Mampu mengoperasikan MS Excel dengan baik (VLOOKUP, Pivot Table)\n4. Teliti dan bertanggung jawab dalam pencatatan barang\n5. Bersedia ditempatkan di area pergudangan Bekasi",
                'description' => 'Bertanggung jawab atas pencatatan administrasi keluar masuk barang di gudang utama, membuat laporan inventaris bulanan, dan melakukan rekonsiliasi data fisik dengan sistem pergudangan secara berkala.',
                'deadline' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Administrasi',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Receptionist Kantor',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Selatan',
                'qualification' => "1. Wanita, usia maks 25 tahun\n2. Tinggi badan minimal 160 cm dengan berat badan proporsional\n3. Pendidikan minimal SMA/SMK/D3\n4. Berpenampilan menarik, ramah, dan komunikatif\n5. Mampu berbahasa Indonesia dengan baik & dasar bahasa Inggris",
                'description' => 'Menerima dan menyambut tamu perusahaan dengan ramah dan sopan, mengarahkan tamu ke departemen terkait, menerima dan meneruskan telepon masuk, serta mengurus distribusi surat menyurat kantor.',
                'deadline' => date('Y-m-d', strtotime('+15 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Administrasi',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Data Entry Clerk',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Tangerang',
                'qualification' => "1. Pria/Wanita, maks 27 tahun\n2. Cepat mengetik (min 50 WPM) dengan tingkat akurasi tinggi\n3. Terbiasa menggunakan Google Sheets, MS Excel, dan Word\n4. Mampu bekerja secara mandiri dengan target waktu yang ketat",
                'description' => 'Melakukan input data operasional harian perusahaan ke dalam database sistem internal secara cepat dan akurat, memeriksa kesalahan input data, serta merapikan arsip digital.',
                'deadline' => date('Y-m-d', strtotime('+20 days')),
                'status' => 'Aktif',
                'job_type' => 'Contract',
                'category' => 'Administrasi',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Executive Assistant',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Barat',
                'qualification' => "1. Wanita, usia maks 30 tahun\n2. Pendidikan minimal D3/S1 Hubungan Internasional/Sekretaris/Manajemen\n3. Mahir berbahasa Inggris aktif secara lisan maupun tulisan\n4. Berpengalaman sebagai asisten direksi minimal 2 tahun\n5. Cekatan, teratur, dan memiliki kemampuan organisasi yang sangat baik",
                'description' => 'Membantu mengatur jadwal pertemuan direksi, menyiapkan dokumen presentasi rapat penting, mengelola perjalanan dinas, serta menjaga kerahasiaan dokumen penting perusahaan.',
                'deadline' => date('Y-m-d', strtotime('+45 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Administrasi',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Staff Payroll (HR Admin)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Barat',
                'qualification' => "1. Pria/Wanita, maks 30 tahun\n2. Pendidikan minimal D3/S1 Akuntansi/Manajemen/Administrasi\n3. Mahir menggunakan MS Excel tingkat lanjut (VLOOKUP, HLOOKUP, IF, PIVOT)\n4. Memahami regulasi ketenagakerjaan dan perhitungan BPJS & PPh 21\n5. Memiliki ketelitian tinggi dan rapi bekerja dengan angka",
                'description' => 'Melakukan rekapitulasi data absensi bulanan karyawan outsourcing, menghitung upah lembur, potongan BPJS Kesehatan & Ketenagakerjaan, PPh 21, membuat slip gaji bulanan, serta memproses pembayaran payroll tepat waktu.',
                'deadline' => date('Y-m-d', strtotime('+25 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Administrasi',
                'experience' => '1-3 Tahun',
            ],

            // === SALES / MARKETING ===
            [
                'title' => 'Sales Canvaser',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Malang',
                'qualification' => "1. Pria/Wanita, maks 35 tahun\n2. Memiliki SIM C aktif dan motor pribadi\n3. Menyukai kerja lapangan dan berorientasi pada target penjualan\n4. Menguasai area Malang Raya dengan baik\n5. Pendidikan minimal SMA/SMK sederajat",
                'description' => 'Mendistribusikan produk FMCG ke toko-toko kelontong dan minimarket di wilayah penugasan, membina hubungan baik dengan pelanggan, serta melakukan penagihan pembayaran.',
                'deadline' => date('Y-m-d', strtotime('+40 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Sales/Marketing',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Telemarketing Officer',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Selatan',
                'qualification' => "1. Pria/Wanita, maks 28 tahun\n2. Memiliki suara yang ramah dan intonasi yang baik\n3. Memiliki keterampilan komunikasi & persuasi yang baik via telepon\n4. Mampu bernegosiasi dan menangani komplain awal konsumen dengan sabar",
                'description' => 'Menghubungi calon konsumen potensial berdasarkan database perusahaan, mempromosikan produk/jasa unggulan mitra, serta melakukan tindak lanjut hingga terjadi kesepakatan penjualan.',
                'deadline' => date('Y-m-d', strtotime('+12 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Sales/Marketing',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Digital Marketing Specialist',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Barat',
                'qualification' => "1. Pria/Wanita, maks 32 tahun\n2. Pendidikan min. D3/S1 Pemasaran/Komunikasi/IT\n3. Pengalaman min 2 tahun mengelola iklan Facebook Ads, Instagram Ads, & Google Ads\n4. Memiliki pemahaman tentang SEO dan copy-writing yang baik\n5. Kreatif dan up-to-date dengan tren digital terkini",
                'description' => 'Merencanakan dan mengeksekusi kampanye pemasaran digital perusahaan di berbagai platform iklan berbayar, menganalisis performa iklan secara mingguan, serta meningkatkan traffic website dan konversi leads.',
                'deadline' => date('Y-m-d', strtotime('+35 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Sales/Marketing',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Account Executive (B2B)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Surabaya',
                'qualification' => "1. Pria/Wanita, usia maks 30 tahun\n2. Pendidikan minimal D3/S1 semua jurusan\n3. Berpenampilan menarik dan percaya diri\n4. Memiliki jaringan relasi korporasi yang luas di Surabaya\n5. Pengalaman minimal 1 tahun di bidang sales B2B / corporate sales",
                'description' => 'Melakukan presentasi bisnis kepada calon klien korporasi, menyusun proposal kerja sama penyediaan tenaga kerja (outsourcing), melakukan negosiasi kontrak harga, dan memastikan kepuasan klien.',
                'deadline' => date('Y-m-d', strtotime('+60 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Sales/Marketing',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'SPG / SPB Counter Mall',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Tangerang',
                'qualification' => "1. Pria/Wanita, maks 26 tahun\n2. Tinggi badan wanita min 158 cm, pria min 168 cm\n3. Berpenampilan menarik, bersih, rapi, dan tidak bau badan\n4. Komunikatif, aktif menawarkan produk, dan ramah\n5. Bersedia bekerja dengan target dan sistem shift counter mall",
                'description' => 'Berjaga di counter brand kosmetik/pakaian ternama mitra PT. Gloria Jasa Mandiri di pusat perbelanjaan, menawarkan produk ke pengunjung mall, menjaga kerapian produk pajangan, serta melaporkan omzet harian.',
                'deadline' => date('Y-m-d', strtotime('+18 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Sales/Marketing',
                'experience' => 'Fresh Graduate',
            ],

            // === F&B / RETAIL ===
            [
                'title' => 'Barista Cafe',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Selatan',
                'qualification' => "1. Pria/Wanita, maks 25 tahun\n2. Pendidikan minimal SMA/SMK\n3. Memiliki ketertarikan tinggi terhadap kopi dan latte art\n4. Ramah, bersih, disiplin, dan komunikatif\n5. Bersedia bekerja shift termasuk akhir pekan dan libur nasional",
                'description' => 'Membuat minuman berbasis kopi dan non-kopi dengan standar kualitas yang ditentukan, merawat mesin espresso secara berkala, melayani order pelanggan, serta menjaga kebersihan area bar.',
                'deadline' => date('Y-m-d', strtotime('+10 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'F&B/Retail',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Pramuniaga Minimarket',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Surabaya',
                'qualification' => "1. Pria/Wanita, maks 24 tahun\n2. Pendidikan minimal SMA/SMK sederajat\n3. Jujur, gesit, dan berpenampilan bersih serta rapi\n4. Bersedia bekerja dengan sistem shift dan masuk saat libur nasional\n5. Mampu bekerja sama dalam tim",
                'description' => 'Menata pajangan barang di rak toko, menjaga kebersihan area minimarket, mengecek tanggal kedaluwarsa produk secara rutin, membantu kasir jika diperlukan, serta melayani konsumen yang berbelanja.',
                'deadline' => date('Y-m-d', strtotime('+14 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'F&B/Retail',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Kitchen Helper Restaurant',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Tangerang',
                'qualification' => "1. Pria/Wanita, usia maks 27 tahun\n2. Diutamakan lulusan SMK Tata Boga atau memiliki ketertarikan memasak\n3. Memahami standar kebersihan dapur dan keamanan makanan\n4. Cepat dalam memotong bahan makanan dan mempersiapkan peralatan masak",
                'description' => 'Membantu koki utama mempersiapkan bahan-bahan masakan (mencuci, mengupas, memotong), membersihkan peralatan dapur, menjaga kebersihan area kerja, dan menata piring saji.',
                'deadline' => date('Y-m-d', strtotime('+22 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'F&B/Retail',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Store Supervisor Retail',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Bekasi',
                'qualification' => "1. Pria/Wanita, maks 32 tahun\n2. Pendidikan minimal D3/S1 semua jurusan\n3. Pengalaman minimal 2 tahun sebagai supervisor retail/toko\n4. Memiliki jiwa kepemimpinan yang kuat dan berorientasi target\n5. Mampu memimpin, mengarahkan, dan mengevaluasi tim toko",
                'description' => 'Mengawasi operasional harian toko retail, memantau pencapaian target penjualan harian/bulanan toko, mengelola persediaan stok barang, serta melatih staff baru (kasir & pramuniaga).',
                'deadline' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'F&B/Retail',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Waiter / Waitress Cafe',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Malang',
                'qualification' => "1. Pria/Wanita, maks 25 tahun\n2. Pendidikan minimal SMA/SMK\n3. Berpenampilan bersih, rapi, ramah, dan murah senyum\n4. Memiliki ingatan yang kuat untuk mencatat pesanan hidangan\n5. Bersedia bekerja shift sore/malam dan hari libur",
                'description' => 'Menyambut kedatangan tamu cafe dengan ramah, memberikan buku menu, mencatat pesanan hidangan, menyajikan makanan dan minuman ke meja tamu, serta membersihkan meja setelah tamu selesai.',
                'deadline' => date('Y-m-d', strtotime('+7 days')),
                'status' => 'Aktif',
                'job_type' => 'Part-time',
                'category' => 'F&B/Retail',
                'experience' => 'Fresh Graduate',
            ],

            // === OPERASIONAL / LAPANGAN ===
            [
                'title' => 'Satpam (Security Guard)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Barat',
                'qualification' => "1. Pria, usia maks 35 tahun, tinggi badan min 168 cm\n2. Memiliki sertifikat pendidikan Gada Pratama aktif\n3. Sehat jasmani dan rohani, tidak bertato & bertindik\n4. Bersedia bekerja dengan sistem shift 12 jam\n5. Pengalaman minimal 1 tahun sebagai satpam/security",
                'description' => 'Menjaga keamanan dan ketertiban area gedung perkantoran, melakukan patroli keliling berkala di area parkir dan dalam gedung, serta mencatat data kendaraan dan tamu keluar masuk.',
                'deadline' => date('Y-m-d', strtotime('+20 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Operasional/Lapangan',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Cleaning Service Kantor',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Selatan',
                'qualification' => "1. Pria/Wanita, usia maks 30 tahun\n2. Pendidikan minimal SMP/SMA\n3. Rajin, jujur, sopan, dan sangat menjaga kebersihan diri\n4. Mengetahui cara penggunaan alat pembersih dan chemical pembersih standar\n5. Bersedia bekerja dengan target kebersihan ruangan",
                'description' => 'Membersihkan seluruh area ruang kerja kantor, toilet, ruang rapat, dan lobi utama, memastikan ketersediaan sabun & tisu toilet, serta mengumpulkan dan membuang sampah harian kantor.',
                'deadline' => date('Y-m-d', strtotime('+15 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Operasional/Lapangan',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Driver Forklift Gudang',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Bekasi',
                'qualification' => "1. Pria, usia maks 38 tahun\n2. Memiliki SIO (Surat Izin Operator) Forklift aktif yang diterbitkan Kemnaker\n3. Menguasai pengoperasian forklift elektrik maupun diesel\n4. Diutamakan berpengalaman di gudang logistik min 2 tahun\n5. Disiplin dan memiliki ketelitian tinggi untuk keselamatan kerja",
                'description' => 'Mengoperasikan armada forklift untuk memindahkan barang atau palet dari area unloading ke rak gudang, memuat barang ke atas truk pengiriman, dan merawat forklift harian.',
                'deadline' => date('Y-m-d', strtotime('+25 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Operasional/Lapangan',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Kurir Motor (Delivery Rider)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Tangerang',
                'qualification' => "1. Pria, usia maks 35 tahun\n2. Memiliki SIM C aktif dan motor pribadi dalam kondisi prima\n3. Memiliki smartphone Android untuk aplikasi kurir & internet lancar\n4. Hafal rute jalan di wilayah Tangerang Kota dan sekitarnya dengan baik\n5. Jujur dan bertanggung jawab",
                'description' => 'Mengambil paket dari hub logistik utama, mengantarkan paket kiriman langsung ke alamat penerima dengan aman dan tepat waktu, serta melakukan verifikasi penerimaan paket di sistem.',
                'deadline' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'Aktif',
                'job_type' => 'Contract',
                'category' => 'Operasional/Lapangan',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Teknisi AC & Listrik Gedung',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Pusat',
                'qualification' => "1. Pria, usia maks 35 tahun\n2. Pendidikan minimal SMK Teknik Elektro/Listrik/Pendingin\n3. Memiliki keahlian melakukan perbaikan & perawatan AC Split/VRF/Cassette\n4. Mengerti jaringan kabel listrik dan panel distribusi tegangan rendah\n5. Pengalaman minimal 2 tahun sebagai teknisi gedung",
                'description' => 'Melakukan pemeliharaan rutin instalasi kelistrikan kantor, memperbaiki kerusakan AC, melakukan pengecekan genset saat terjadi pemadaman, serta menangani keluhan teknis gedung.',
                'deadline' => date('Y-m-d', strtotime('+28 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Operasional/Lapangan',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Operator Produksi Pabrik',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Surabaya',
                'qualification' => "1. Pria/Wanita, maks 25 tahun\n2. Pendidikan minimal SMA/SMK (diutamakan rumpun Teknik)\n3. Sehat fisik, mata normal (tidak minus/silinder), tidak buta warna\n4. Bersedia bekerja dalam sistem shift bergilir (3 shift)\n5. Memiliki daya tahan tubuh yang baik dan disiplin tinggi",
                'description' => 'Mengoperasikan mesin manufaktur pabrik perakitan atau pengemasan makanan, menjaga kelancaran proses lini produksi, menyortir produk cacat (reject), serta merapikan area kerja.',
                'deadline' => date('Y-m-d', strtotime('+40 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Operasional/Lapangan',
                'experience' => 'Fresh Graduate',
            ],

            // === TEKNOLOGI / IT ===
            [
                'title' => 'IT Support Specialist',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Pusat',
                'qualification' => "1. Pria, usia maks 28 tahun\n2. Pendidikan minimal D3/S1 Teknik Informatika/Sistem Informasi\n3. Memahami troubleshooting hardware, software, OS Windows/macOS\n4. Mengerti dasar jaringan LAN/WAN, router, WiFi, dan IP Address\n5. Cepat belajar, ramah, dan solutif dalam melayani keluhan pengguna",
                'description' => 'Membantu karyawan kantor dalam menyelesaikan kendala teknis komputer, printer, instalasi software, jaringan internet lambat, serta melakukan maintenance berkala PC kantor.',
                'deadline' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Teknologi/IT',
                'experience' => 'Fresh Graduate',
            ],
            [
                'title' => 'Mobile Developer (Flutter)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Barat',
                'qualification' => "1. Pria/Wanita, maks 35 tahun\n2. Pendidikan minimal D3/S1 rumpun IT\n3. Pengalaman minimal 2 tahun membangun aplikasi mobile menggunakan Flutter (Dart)\n4. Mahir mengintegrasikan Rest API dan mengelola State Management (Provider/Bloc/GetX)\n5. Memiliki portofolio aplikasi yang sudah dipublikasikan di Play Store/App Store",
                'description' => 'Mengembangkan fitur-fitur baru pada aplikasi internal mobile perusahaan berbasis Flutter, melakukan bug fixing, berkoordinasi dengan backend developer untuk integrasi API, serta meningkatkan performa app.',
                'deadline' => date('Y-m-d', strtotime('+45 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Teknologi/IT',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'Web Developer (Laravel)',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Malang',
                'qualification' => "1. Pria/Wanita, maks 30 tahun\n2. Menguasai PHP framework Laravel dengan sangat baik\n3. Memahami database MySQL, indexing, dan query optimization\n4. Mengerti RESTful API Design & Git version control\n5. Pengalaman minimal 1 tahun di posisi sejenis",
                'description' => 'Membangun dan memelihara sistem portal web rekrutmen PT. Gloria Jasa Mandiri, mengembangkan modul backend admin panel, menulis API untuk aplikasi mobile, serta memastikan keamanan web dari kerentanan umum.',
                'deadline' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'Aktif',
                'job_type' => 'Full-time',
                'category' => 'Teknologi/IT',
                'experience' => '1-3 Tahun',
            ],
            [
                'title' => 'UI/UX Designer',
                'company_name' => 'PT. Gloria Jasa Mandiri',
                'location' => 'Jakarta Selatan',
                'qualification' => "1. Pria/Wanita, maks 28 tahun\n2. Mahir menggunakan tools design seperti Figma, Adobe XD, Photoshop\n3. Memahami proses perancangan User Flow, Wireframe, Prototyping, & Design System\n4. Memiliki portofolio desain UI web / mobile yang menarik dan user-friendly\n5. Mampu bekerja sama dengan Product Manager dan Software Engineer",
                'description' => 'Membuat desain antarmuka pengguna (UI) dan alur pengalaman pengguna (UX) untuk aplikasi web dan mobile portal rekrutmen perusahaan, membuat prototipe interaktif untuk usability testing, serta menjaga konsistensi visual.',
                'deadline' => date('Y-m-d', strtotime('+15 days')),
                'status' => 'Aktif',
                'job_type' => 'Contract',
                'category' => 'Teknologi/IT',
                'experience' => '1-3 Tahun',
            ],
        ];

        // Seeding data lowongan pekerjaan
        foreach ($jobs as $jobData) {
            Job::create($jobData);
        }
    }
}
